### ISSUE TITLE
Instell Support

### ISSUE THREAD

**Issue by svm420** [camlost2/AJE#21]
Don't know if this is planned or wanted, but thought a github issue would be the best place. Would love support for [this mod](http://forum.kerbalspaceprogram.com/threads/119735-1-0-2-Instell-Incorporated-Experimental-Technologies) when you have time if its possible. Looking forward to trying AJE.

**Comment by camlost2** [comment]
Scramjets had been suggested by many since long time ago, but the physics is very different from regular engines, and beyond my knowledge. But anyone is welcome to read the code of AJESolverTester and think about it, the online documentation should be enough.

WTF is an ElectricTurboFan?

**Comment by blowfishpro** [comment]
Unfortunately there's no model for scramjets currently as the equations governing their operation are not known and all test data is classified.  The inlet and nozzle could probably be modeled, but how exactly the combustion works is a big unknown.
