### ISSUE TITLE
TPRCurves have weird kinks in them

### ISSUE THREAD

**Issue by blowfishpro** [camlost2/AJE#26]
Setting all the tangents to zero makes them somewhat less than smooth.  Could just adjust the tangents until they look smooth, but if they're based on actual data somewhere then that should be used.

**Comment by NathanKell** [comment]
The J58's TPRCurve is based--in its points--on the best info I could glean. No idea about the slope, it was supposed to just be flat until the start of decrease, linear to end of decrease, flat again. I'll pop it into Unity and fix.

**Comment by blowfishpro** [comment]
This is what I'm talking about:

![ajetprcurves](https://cloud.githubusercontent.com/assets/10545461/8248187/c1643b64-1610-11e5-8273-5394660d449b.png)

Near the control points, the TPR curves are flat (because their tangents are zero), but this makes them somewhat less than smooth.

**Comment by NathanKell** [comment]
Ah, crap, right, misread and thought you were talking about the engine curves. Yeah, these need to be fixed.

**Comment by blowfishpro** [comment]
![ajetprcurves](https://cloud.githubusercontent.com/assets/10545461/8266396/cdc54a84-16e1-11e5-9a60-5546d6117539.png)

Thanks, looks much better now.
