### ISSUE TITLE
Meredith Effect and Exhaust Thrust Not Applied

### ISSUE THREAD

**Issue by ferram4** [camlost2/AJE#35]
Although PistonEngine calculates thrust from the exhaust and the Meredith effect in its Update function, this thrust is not used; in SolverPropeller, while the combined effect is read from PistonEngine [here](https://github.com/camlost2/AJE/blob/solver_redo/Source/SolverPropeller.cs#L185) it is never added to EngineSolver.thrust and so never enters the calculations.

In addition, in AJEPropeller [these two readouts](https://github.com/camlost2/AJE/blob/solver_redo/Source/AJEPropeller.cs#L87-L91) are never set and so constantly read zero.

A quick hack to update that readout and to add the thrust did result in expected physics behavior, but not expected readout behavior: on the DoubleWasp R-2800-18W the combination of exhaust and Meredith thrust resulted in ~1kN of thrust across all speed ranges, as confirmed by the difference between the ModuleEngines total thrust readout and the AJEPropeller prop thrust readout.  However, the thrust from the exhaust was read as ~1000 kN, while the thrust from the Meredith effect was read as ~25 kN.

This was a result of storing the values calculated [here](https://github.com/camlost2/AJE/blob/solver_redo/Source/PistonEngine.cs#L612-L619) in a variable to be read for the readout; these are the same exact values that were added to prop thrust, so I'm at something of a loss as to how this happened.

**Comment by NathanKell** [comment]
Probably something screwy in my reworking the calcs. Been so swamped I haven't had a chance to touch it yet, sorry.

**Comment by ferram4** [comment]
This is resolved by #36, so closing.
