### ISSUE TITLE
1.0.5 support

### ISSUE THREAD

**Issue by blowfishpro** [camlost2/AJE#43]
### Changes
- The Juno will be the new J85 (no longer a basic jet clone)
- Curent TRJ clones should now be Panther clones
- F404 should also be a Panther clone
- Basic jet (Wheezley) should be modeled as CF34 or similar
- F100 will be the default Panther (vectoring removed)
- New Panther clone should preserve vectoring
  *\* Candidates: AL31/41 (though we already have a lot of those), RD-33, or experimental F100/F110 variants used on F-15 ACTIVE or F-16 VISTA
- Remove afterburning engine module on Panther and clones and incorporate afterburning FX (with correct thresholds) into main module
  - Probably do this once before clones are created
    - Non-afterburning variants can remove it themselves
      - Alternately, create a non-afterburning template, which is removed before MM finishes
- 2.5m turbofan (Goliath) modeled as CF6 or similar
  - Consider converting B9 CF6 to a newer engine, but that can wait
- Make sure changed intakes are set up correctly
  - Subsonic radial intake may have different area
  - Fuselage intake is now DSI and may have different area
  - 2.5m jet (Goliath) has a built in intake
  - New 0.625m subsonic intake?

**Comment by NathanKell** [comment]
Looks good to me. The Goliath's stock stats (minus thrust/mass) are off the CF6, so that's fitting. The BJE's stats are the JT8D-219 (ditto), though I don't know what @Porkjet based the model off.

**Comment by Porkjet** [comment]
The model is based off the GE90-115B. Since reaching size2 diameter at
0.64x scale pretty much required taking the biggest thing we have as
reference

2015-11-10 1:05 GMT+01:00 NathanKell notifications@github.com:

**Comment by Porkjet** [comment]
BJE is just a happy mixture of whatever elements of other airliner engines
seemed right, Panther model is based off the EJ-200 eurofighter engine

2015-11-10 15:22 GMT+01:00 Chris T. porkjet90@gmail.com:

**Comment by dearmoon9** [comment]
As Porkjet said Goliath should be modeled as GE90-115B, not another CF6 (we already have one from B9), also it would be fine to make copy of it and model it as Rolls-Royce Trent:
https://en.wikipedia.org/wiki/Rolls-Royce_Trent

**Comment by blowfishpro** [comment]
The GE90 is way to big for stock KSP.  If RO wants to make a rescale then that's fine, but AJE has to be designed to be stock part scale compatible.  I was planning to modify the AJE CF6 to be something newer, possibly in the PW1000 or CFM LEAP series depending on what I can get data for.

**Comment by NathanKell** [comment]
Heh. The stock one has a 360kN static thrust anyway.

**Comment by NathanKell** [comment]
@Porkjet I find that particularly ironic since the EJ-200 is specifically known for _not_ vectoring. :P
