### ISSUE TITLE
Get SABRE and RAPIER RF fuel setup moved to RO and RF Stockalike

### ISSUE THREAD

**Issue by blowfishpro** [camlost2/AJE#44]
Suggested by ialdabaoth (who is awesome) - the correct place to switch the fuel to methane/methalox or hydrogen/hydrolox is in the RF engine configs, not in AJE

**Comment by NathanKell** [comment]
Concur. Tagging @Raptor831 for Stockalike RF, and, err, me for RO.

**Comment by Raptor831** [comment]
Just added the non-RO elements to the RFStockalike repo.

**Comment by blowfishpro** [comment]
Still have to deal with B9 and MkIV engines, but done for stock RAPIER

**Comment by blowfishpro** [comment]
Fuel patches can be removed when Raptor831/RFStockalike#54 is merged

**Comment by Raptor831** [comment]
Merged on my end. Thanks @blowfishpro.

**Comment by blowfishpro** [comment]
Done now
