### ISSUE TITLE
Jets are using LiquidFuel now instead of Kerosene

### ISSUE THREAD

**Issue by dearmoon9** [camlost2/AJE#45]
I just noticed that now lots of jet engines (especially from B9) and props from KAX are using LiquidFuel instead of Kerosene. I remember that this wasn't an issue a couple of months ago.

Also from some reason RAPIER and B9 Sabre engines are using stock values for their ISP.

**Comment by NathanKell** [comment]
@winged7 I specifically pointed you towards #44 in [this comment here](https://github.com/KSP-RO/RP-0/pull/297#issuecomment-156560032) ;)
