### ISSUE TITLE
CF34-3B mass is too high

### ISSUE THREAD

**Issue by tsbockman** [camlost2/AJE#49]
The CF34-3B's mass should be about 750 kg, according to [Wikipedia](https://en.wikipedia.org/wiki/General_Electric_CF34). Currently AJE has it as 4100 kg, which I'm guessing was copy-pasta-ed from the CF6-50E entry.

I haven't checked to see if the Wikipedia number is actually correct, but I'm sure it is at least much closer to the truth, given the relative size and power of the two engines.

**Comment by blowfishpro** [comment]
I'll take a look

**Comment by blowfishpro** [comment]
Fixed
