### ISSUE TITLE
SABRE Engines - config broken

### ISSUE THREAD

**Issue by dearmoon9** [camlost2/AJE#55]
I've just noticed that SABRE engines lost their RO configuration.

http://i.imgur.com/b6UeenK.png

**Comment by blowfishpro** [comment]
AJE never assigned ModuleEnginesRF, but the configs that assigned the fuel type were moved out of AJE (because that's not where they belong).  @NathanKell were those configs ever added to RO?

**Comment by NathanKell** [comment]
Will be fixed in next RO.
