### ISSUE TITLE
Smaller jet engines don't produce any visual effects 

### ISSUE THREAD

**Issue by dearmoon9** [camlost2/AJE#56]
As in the picture below:
http://i.imgur.com/6juPXfe.png
-Nene
-Derwent
-FJ-44
 They don't produce any visual effects.

That's what it looked like in KSP 1.0.4 (Nene):
http://i.imgur.com/vOmf3HQ.png - you can clearly see light from the engine.

Bigger engines (from various mods) work properly.
Not sure if this is RO or AJE issue.

**Comment by blowfishpro** [comment]
They should be producing smoke effects at least.  Are they?

Non-afterburning jets don't usually produce any visible glow or flame.  The way it worked before isn't really correct.

Also FYI, the Derwent is added by RO, not AJE.

**Comment by dearmoon9** [comment]
i don't see any smoke effects.

So deleting such glow was intentional? May I ask how to bring back 1.0.4 configs for Nene?

**Comment by blowfishpro** [comment]
There does seem to be an issue preventing the smoke effects from showing up (haven't confirmed if it's an issue with AJE or B9 yet ... my problem either way I guess).  There also seems to be an issue with the animations on the YJ93 and F119.

If you wanted the glow back, you would have to switch the animation module to FXAnimateThrottle.

**Comment by blowfishpro** [comment]
Confirmed that missing smoke is a B9 issue.  I fixed the other issues with the YJ93 and F119, so I think we're done here.
