### ISSUE TITLE
Thrust Limiter with ModuleEnginesAJERotor

### ISSUE THREAD

**Issue by svm420** [camlost2/AJE#57]
Currently the thrust limiter only appears to affect thrust in the editor. Upon going into flight the thrust limiter has no effect on output.

**Comment by blowfishpro** [comment]
https://github.com/camlost2/AJE/blob/solver_redo/Source/AJERotor.cs#L81

For reference when I actually get around to this ... it should multiply by `thrustPercentage * 0.01`

**Comment by blowfishpro** [comment]
Should be fixed now
